/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AnimeRouteImport } from './routes/anime'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ClassicsRouteImport } from './routes/classics'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as KidsRouteImport } from './routes/kids'
import { Route as MangaRouteImport } from './routes/manga'
import { Route as MoviesRouteImport } from './routes/movies'
import { Route as NewRouteImport } from './routes/new'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SeriesRouteImport } from './routes/series'
import { Route as TrendingRouteImport } from './routes/trending'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedProfilesRouteImport } from './routes/_authenticated/profiles'
import { Route as AuthenticatedWatchlistRouteImport } from './routes/_authenticated/watchlist'
import { Route as ArabicIndexRouteImport } from './routes/arabic.index'
import { Route as ArabicCountryRouteImport } from './routes/arabic.$country'
import { Route as CollectionsIndexRouteImport } from './routes/collections.index'
import { Route as CollectionsSlugRouteImport } from './routes/collections.$slug'
import { Route as RamadanIndexRouteImport } from './routes/ramadan.index'
import { Route as RamadanYearRouteImport } from './routes/ramadan.$year'
import { Route as TitleSlugRouteImport } from './routes/title.$slug'
import { Route as WatchSlugRouteImport } from './routes/watch.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimeRoute = AnimeRouteImport.update({
  id: '/anime',
  path: '/anime',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassicsRoute = ClassicsRouteImport.update({
  id: '/classics',
  path: '/classics',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const KidsRoute = KidsRouteImport.update({
  id: '/kids',
  path: '/kids',
  getParentRoute: () => rootRouteImport,
} as any)
const MangaRoute = MangaRouteImport.update({
  id: '/manga',
  path: '/manga',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesRoute = MoviesRouteImport.update({
  id: '/movies',
  path: '/movies',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesRoute = SeriesRouteImport.update({
  id: '/series',
  path: '/series',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendingRoute = TrendingRouteImport.update({
  id: '/trending',
  path: '/trending',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfilesRoute = AuthenticatedProfilesRouteImport.update({
  id: '/profiles',
  path: '/profiles',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWatchlistRoute = AuthenticatedWatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ArabicIndexRoute = ArabicIndexRouteImport.update({
  id: '/arabic/',
  path: '/arabic/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArabicCountryRoute = ArabicCountryRouteImport.update({
  id: '/arabic/$country',
  path: '/arabic/$country',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsSlugRoute = CollectionsSlugRouteImport.update({
  id: '/collections/$slug',
  path: '/collections/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RamadanIndexRoute = RamadanIndexRouteImport.update({
  id: '/ramadan/',
  path: '/ramadan/',
  getParentRoute: () => rootRouteImport,
} as any)
const RamadanYearRoute = RamadanYearRouteImport.update({
  id: '/ramadan/$year',
  path: '/ramadan/$year',
  getParentRoute: () => rootRouteImport,
} as any)
const TitleSlugRoute = TitleSlugRouteImport.update({
  id: '/title/$slug',
  path: '/title/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchSlugRoute = WatchSlugRouteImport.update({
  id: '/watch/$slug',
  path: '/watch/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anime': typeof AnimeRoute
  '/auth': typeof AuthRoute
  '/classics': typeof ClassicsRoute
  '/explore': typeof ExploreRoute
  '/kids': typeof KidsRoute
  '/manga': typeof MangaRoute
  '/movies': typeof MoviesRoute
  '/new': typeof NewRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/series': typeof SeriesRoute
  '/trending': typeof TrendingRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/profiles': typeof AuthenticatedProfilesRoute
  '/watchlist': typeof AuthenticatedWatchlistRoute
  '/arabic/$country': typeof ArabicCountryRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/ramadan/$year': typeof RamadanYearRoute
  '/title/$slug': typeof TitleSlugRoute
  '/watch/$slug': typeof WatchSlugRoute
  '/arabic/': typeof ArabicIndexRoute
  '/collections/': typeof CollectionsIndexRoute
  '/ramadan/': typeof RamadanIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anime': typeof AnimeRoute
  '/auth': typeof AuthRoute
  '/classics': typeof ClassicsRoute
  '/explore': typeof ExploreRoute
  '/kids': typeof KidsRoute
  '/manga': typeof MangaRoute
  '/movies': typeof MoviesRoute
  '/new': typeof NewRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/series': typeof SeriesRoute
  '/trending': typeof TrendingRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/profiles': typeof AuthenticatedProfilesRoute
  '/watchlist': typeof AuthenticatedWatchlistRoute
  '/arabic/$country': typeof ArabicCountryRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/ramadan/$year': typeof RamadanYearRoute
  '/title/$slug': typeof TitleSlugRoute
  '/watch/$slug': typeof WatchSlugRoute
  '/arabic': typeof ArabicIndexRoute
  '/collections': typeof CollectionsIndexRoute
  '/ramadan': typeof RamadanIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/anime': typeof AnimeRoute
  '/auth': typeof AuthRoute
  '/classics': typeof ClassicsRoute
  '/explore': typeof ExploreRoute
  '/kids': typeof KidsRoute
  '/manga': typeof MangaRoute
  '/movies': typeof MoviesRoute
  '/new': typeof NewRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/series': typeof SeriesRoute
  '/trending': typeof TrendingRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/profiles': typeof AuthenticatedProfilesRoute
  '/_authenticated/watchlist': typeof AuthenticatedWatchlistRoute
  '/arabic/$country': typeof ArabicCountryRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/ramadan/$year': typeof RamadanYearRoute
  '/title/$slug': typeof TitleSlugRoute
  '/watch/$slug': typeof WatchSlugRoute
  '/arabic/': typeof ArabicIndexRoute
  '/collections/': typeof CollectionsIndexRoute
  '/ramadan/': typeof RamadanIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anime'
    | '/auth'
    | '/classics'
    | '/explore'
    | '/kids'
    | '/manga'
    | '/movies'
    | '/new'
    | '/reset-password'
    | '/search'
    | '/series'
    | '/trending'
    | '/admin'
    | '/profiles'
    | '/watchlist'
    | '/arabic/$country'
    | '/collections/$slug'
    | '/ramadan/$year'
    | '/title/$slug'
    | '/watch/$slug'
    | '/arabic/'
    | '/collections/'
    | '/ramadan/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anime'
    | '/auth'
    | '/classics'
    | '/explore'
    | '/kids'
    | '/manga'
    | '/movies'
    | '/new'
    | '/reset-password'
    | '/search'
    | '/series'
    | '/trending'
    | '/admin'
    | '/profiles'
    | '/watchlist'
    | '/arabic/$country'
    | '/collections/$slug'
    | '/ramadan/$year'
    | '/title/$slug'
    | '/watch/$slug'
    | '/arabic'
    | '/collections'
    | '/ramadan'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/anime'
    | '/auth'
    | '/classics'
    | '/explore'
    | '/kids'
    | '/manga'
    | '/movies'
    | '/new'
    | '/reset-password'
    | '/search'
    | '/series'
    | '/trending'
    | '/_authenticated/admin'
    | '/_authenticated/profiles'
    | '/_authenticated/watchlist'
    | '/arabic/$country'
    | '/collections/$slug'
    | '/ramadan/$year'
    | '/title/$slug'
    | '/watch/$slug'
    | '/arabic/'
    | '/collections/'
    | '/ramadan/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AnimeRoute: typeof AnimeRoute
  AuthRoute: typeof AuthRoute
  ClassicsRoute: typeof ClassicsRoute
  ExploreRoute: typeof ExploreRoute
  KidsRoute: typeof KidsRoute
  MangaRoute: typeof MangaRoute
  MoviesRoute: typeof MoviesRoute
  NewRoute: typeof NewRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  SeriesRoute: typeof SeriesRoute
  TrendingRoute: typeof TrendingRoute
  ArabicCountryRoute: typeof ArabicCountryRoute
  CollectionsSlugRoute: typeof CollectionsSlugRoute
  RamadanYearRoute: typeof RamadanYearRoute
  TitleSlugRoute: typeof TitleSlugRoute
  WatchSlugRoute: typeof WatchSlugRoute
  ArabicIndexRoute: typeof ArabicIndexRoute
  CollectionsIndexRoute: typeof CollectionsIndexRoute
  RamadanIndexRoute: typeof RamadanIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anime': {
      id: '/anime'
      path: '/anime'
      fullPath: '/anime'
      preLoaderRoute: typeof AnimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classics': {
      id: '/classics'
      path: '/classics'
      fullPath: '/classics'
      preLoaderRoute: typeof ClassicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kids': {
      id: '/kids'
      path: '/kids'
      fullPath: '/kids'
      preLoaderRoute: typeof KidsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manga': {
      id: '/manga'
      path: '/manga'
      fullPath: '/manga'
      preLoaderRoute: typeof MangaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies': {
      id: '/movies'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof MoviesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series': {
      id: '/series'
      path: '/series'
      fullPath: '/series'
      preLoaderRoute: typeof SeriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trending': {
      id: '/trending'
      path: '/trending'
      fullPath: '/trending'
      preLoaderRoute: typeof TrendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profiles': {
      id: '/_authenticated/profiles'
      path: '/profiles'
      fullPath: '/profiles'
      preLoaderRoute: typeof AuthenticatedProfilesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/watchlist': {
      id: '/_authenticated/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof AuthenticatedWatchlistRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/arabic/': {
      id: '/arabic/'
      path: '/arabic'
      fullPath: '/arabic/'
      preLoaderRoute: typeof ArabicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arabic/$country': {
      id: '/arabic/$country'
      path: '/arabic/$country'
      fullPath: '/arabic/$country'
      preLoaderRoute: typeof ArabicCountryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/': {
      id: '/collections/'
      path: '/collections'
      fullPath: '/collections/'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$slug': {
      id: '/collections/$slug'
      path: '/collections/$slug'
      fullPath: '/collections/$slug'
      preLoaderRoute: typeof CollectionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ramadan/': {
      id: '/ramadan/'
      path: '/ramadan'
      fullPath: '/ramadan/'
      preLoaderRoute: typeof RamadanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ramadan/$year': {
      id: '/ramadan/$year'
      path: '/ramadan/$year'
      fullPath: '/ramadan/$year'
      preLoaderRoute: typeof RamadanYearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/title/$slug': {
      id: '/title/$slug'
      path: '/title/$slug'
      fullPath: '/title/$slug'
      preLoaderRoute: typeof TitleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$slug': {
      id: '/watch/$slug'
      path: '/watch/$slug'
      fullPath: '/watch/$slug'
      preLoaderRoute: typeof WatchSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedProfilesRoute: typeof AuthenticatedProfilesRoute
  AuthenticatedWatchlistRoute: typeof AuthenticatedWatchlistRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedProfilesRoute: AuthenticatedProfilesRoute,
  AuthenticatedWatchlistRoute: AuthenticatedWatchlistRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AnimeRoute: AnimeRoute,
  AuthRoute: AuthRoute,
  ClassicsRoute: ClassicsRoute,
  ExploreRoute: ExploreRoute,
  KidsRoute: KidsRoute,
  MangaRoute: MangaRoute,
  MoviesRoute: MoviesRoute,
  NewRoute: NewRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  SeriesRoute: SeriesRoute,
  TrendingRoute: TrendingRoute,
  ArabicCountryRoute: ArabicCountryRoute,
  CollectionsSlugRoute: CollectionsSlugRoute,
  RamadanYearRoute: RamadanYearRoute,
  TitleSlugRoute: TitleSlugRoute,
  WatchSlugRoute: WatchSlugRoute,
  ArabicIndexRoute: ArabicIndexRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
  RamadanIndexRoute: RamadanIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
